import React from "react";
import Head from "next/head";
import { Inter } from "next/font/google";
import { ClerkProvider } from "@clerk/nextjs";
import Upload from "../../components/Upload";
const inter = Inter({ subsets: ["latin"] });

const index = () => {
  return (
    <ClerkProvider>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={`${inter.className}`}>
        <Upload />
      </main>
    </ClerkProvider>
  );
};

export default index;
